# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: hobbit-links
provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:eu-west-1:*:table/LinkTable

functions:
  docs:
    handler: src/docs.get_docs
    events:
      - http:
          path: get_docs
          method: get
  add_link:
    handler: src/add_link.add_link
    events:
      - http:
          path: link
          method: post
  get_link:
    handler: src/get_link.get_link
    events:
      - http:
          path: link/{link}
          method: get
  delete_link:
    handler: src/delete_link.delete_link
    events:
      - http:
          path: link/{link}
          method: delete


resources:
  Resources:
    LinkTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "LinkTable"
        AttributeDefinitions:
        - AttributeName: "alias"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "alias"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: timeToLive
          Enabled: true
